'use strict';

// format-flipper — the Format Flipper conversion engine as a Node library.
//
// The engine code in engine.js is generated byte-for-byte from the
// browser tool (https://toolymctoolface.com/format/), so this package
// converts exactly like the web page does. Twelve formats, any
// direction, plain JavaScript values in the middle.

const jsyaml = require('js-yaml');
const { DOMParser } = require('./dom-shim');
const createEngine = require('./engine');

const { PARSERS, SERIALIZERS } = createEngine({ jsyaml }, DOMParser);

const FORMATS = Object.keys(PARSERS);

const FORMAT_EXT = {
  json: 'json', ndjson: 'ndjson', yaml: 'yaml', toml: 'toml',
  ini: 'ini', properties: 'properties', csv: 'csv', tsv: 'tsv',
  xml: 'xml', md: 'md', html: 'html', sql: 'sql',
};

// Extensions that map to a format but are not the canonical one.
const EXT_ALIASES = {
  yml: 'yaml', markdown: 'md', htm: 'html', jsonl: 'ndjson', props: 'properties',
};

const DEFAULT_OPTS = {
  jsonIndent: 2,
  yamlIndent: 2,
  xmlIndent: 2,
  xmlRoot: 'rows',
  xmlItem: 'row',
  sqlTable: 'data',
  sqlQuote: 'backtick',
  coerceTypes: true,
  strictParse: false,
  csvDelimiterIn: 'comma',
  csvDelimiterOut: 'comma',
};

function formatForExtension(ext) {
  const e = String(ext || '').toLowerCase().replace(/^\./, '');
  if (FORMAT_EXT[e]) return e;
  return EXT_ALIASES[e] || null;
}

function parse(input, from, opts) {
  if (!PARSERS[from]) throw new Error(`unknown source format: ${from}`);
  return PARSERS[from](String(input), { ...DEFAULT_OPTS, ...opts });
}

function serialize(value, to, opts) {
  if (!SERIALIZERS[to]) throw new Error(`unknown target format: ${to}`);
  return SERIALIZERS[to](value, { ...DEFAULT_OPTS, ...opts });
}

function convert(input, from, to, opts) {
  const merged = { ...DEFAULT_OPTS, ...opts };
  if (!PARSERS[from]) throw new Error(`unknown source format: ${from}`);
  if (!SERIALIZERS[to]) throw new Error(`unknown target format: ${to}`);
  return SERIALIZERS[to](PARSERS[from](String(input), merged), merged);
}

module.exports = {
  convert,
  parse,
  serialize,
  formatForExtension,
  PARSERS,
  SERIALIZERS,
  FORMATS,
  FORMAT_EXT,
  DEFAULT_OPTS,
};
