'use strict';

// Sign a Pro license key.
//
//   node tools/sign-license.js <email> [path/to/signing-key.pem]
//
// Defaults to the committed DEMO key (tools/demo-license-key.pem) so the
// flow is testable end-to-end. Production keys must be signed with a
// private key generated by tools/generate-license-keypair.js and kept
// out of the repository.
//
// Key format: FF1.<base64url payload>.<base64url signature>
// Payload: {"email": ..., "plan": "pro", "issued": "YYYY-MM-DD"}
// The page verifies the signature offline with WebCrypto against the
// embedded public key — validating a license never makes a network call.

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

const email = process.argv[2];
if (!email) {
  console.error('usage: node tools/sign-license.js <email> [signing-key.pem]');
  process.exit(1);
}
const keyPath = process.argv[3] || path.join(__dirname, 'demo-license-key.pem');
const privateKey = crypto.createPrivateKey(fs.readFileSync(keyPath, 'utf8'));

const payload = Buffer.from(JSON.stringify({
  email,
  plan: 'pro',
  issued: new Date().toISOString().slice(0, 10),
}));
const signature = crypto.sign(null, payload, privateKey);

const b64u = b => b.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
console.log(`FF1.${b64u(payload)}.${b64u(signature)}`);
